#!/bin/sh

VAULT_VERSION="1.1.1"
VAULT_DOWNLOAD="https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip"
CONSUL_TEMPLATE_VERSION="0.19.5"
CONSUL_TEMPLATE_DOWNLOAD="https://releases.hashicorp.com/consul-template/${CONSUL_TEMPLATE_VERSION}/consul-template_${CONSUL_TEMPLATE_VERSION}_linux_amd64.zip"
ENVCONSUL_VERSION="0.7.3"
ENVCONSUL_DOWNLOAD="https://releases.hashicorp.com/envconsul/${ENVCONSUL_VERSION}/envconsul_${ENVCONSUL_VERSION}_linux_amd64.zip"

# Update and install supporting software
sudo apt update -y
#sudo apt install -y unzip mysql-server jq
sudo apt install -y unzip jq
echo "Run sudo apt install -y mysql-server manually"

# Download and install Vault, consul-template and envconsul
curl -so vault.zip ${VAULT_DOWNLOAD}
#curl -so consul-template.zip ${CONSUL_TEMPLATE_DOWNLOAD}
#curl -so envconsul.zip ${ENVCONSUL_DOWNLOAD}

unzip vault.zip
#unzip consul-template.zip
#unzip envconsul.zip

install -d bin

#sudo install vault consul-template envconsul bin
sudo install vault bin

#rm -f vault vault.zip consul-template consul-template.zip envconsul envconsul.zip
rm -f vault vault.zip
